### ISSUE TITLE
Where's the README?

### ISSUE THREAD

**Issue by ilbuonmarcio** [Bonoldiz/react-boilerplate#1]
What should I do with that?
I need HAAAALP!

**Comment by ilbuonmarcio** [comment]
Oh, now I see, there's an `instructions.md` file in the project root.

I suggest you to rename it to README.md for making sure it will be read!

**Comment by Bonoldiz** [comment]
"Instructions" reminds me about something to do absolutely.
A day I'll add a well formed README.md.
